# Etapa de construcción (build stage)
FROM node:13.12.0-alpine AS build-stage

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración del proyecto (package.json y package-lock.json)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código fuente de la aplicación React
COPY . .

# Compila la aplicación React
RUN npm run build

# Etapa de producción
FROM nginx:alpine AS production-stage

# Copia los archivos construidos desde la etapa de construcción
COPY --from=build-stage /app/build /usr/share/nginx/html

# Expone el puerto en el que Nginx servirá la aplicación (por defecto 80)

# Inicia el servidor web Nginx
CMD ["nginx", "-g", "daemon off;"]
